# Generated by Django 3.1.3 on 2021-01-09 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(null=True)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
