# Generated by Django 2.2.7 on 2019-11-08 22:09

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
