# Generated by Django 2.2.7 on 2019-11-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191108_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.URLField(default="{% url 'page:index' %}"),
        ),
    ]
