# Generated by Django 2.2.7 on 2019-11-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='desc',
            field=models.TextField(default='default description'),
        ),
    ]
