# Generated by Django 3.1.3 on 2021-01-09 02:18

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import markdownx.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid')])),
                ('content', markdownx.models.MarkdownxField(max_length=512)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
